# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1433193870);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1433194334);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1433194214);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.blocked", "{\"FWOQG7K0DIoR7IfVX99rIg==\":1,\"A2WNM340R8X/tRM8wN1MJQ==\":1,\"BcOAbuLi77y1AyoMYVR3Gg==\":1,\"XN0gzX5CZdmIYOEKmV0GVA==\":1,\"FD+HVOI6BkuwDht8E4Js3g==\":1,\"houJ+qdAQiE2vbUnKlgzdQ==\":1,\"5dPX2t2Xtq7V1dnRJu5irg==\":1,\"fN+l9WzvM5iUCIvEhEOYEQ==\":1,\"eZj1PVWGhpGfRIQaMb7GzA==\":1,\"24lPHRAkVJVXByz3pR2M/g==\":1,\"l9Y1wE6PrMx+3VW3g1dJ2Q==\":1,\"YsGswnfPkVNPe2jtF77GMA==\":1,\"t+kxXzmddH51Tb2XAG7VBg==\":1,\"+FGfbQqQI6PtMPCLu5tZ7Q==\":1,\"ZWzxIoKFFSaKQz/6tw9dvA==\":1}");
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "DE");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150511103818");
user_pref("browser.slowStartup.averageTime", 1970);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150511103818");
user_pref("browser.startup.homepage_override.mstone", "38.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1433275279594");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1433189343788");
user_pref("datareporting.policy.firstRunTime", "1433188879593");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1352);
user_pref("datareporting.sessions.current.main", 31);
user_pref("datareporting.sessions.current.sessionRestored", 1664);
user_pref("datareporting.sessions.current.startTime", "1433196960866");
user_pref("datareporting.sessions.current.totalTime", 5);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1433188878489,\"a\":6,\"t\":27,\"c\":false,\"m\":131,\"fp\":2285,\"sr\":2545}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1433189331445,\"a\":4,\"t\":22,\"c\":false,\"m\":263,\"fp\":2049,\"sr\":2295}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1433193749564,\"a\":34,\"t\":177,\"c\":true,\"m\":180,\"fp\":1945,\"sr\":2238}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1433194093078,\"a\":38,\"t\":312,\"c\":true,\"m\":111,\"fp\":1723,\"sr\":2148}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1433194799303,\"a\":7,\"t\":35,\"c\":true,\"m\":153,\"fp\":1390,\"sr\":1701}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1433196691833,\"a\":1,\"t\":9,\"c\":true,\"m\":171,\"fp\":1912,\"sr\":2400}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1433196851984,\"a\":9,\"t\":50,\"c\":true,\"m\":129,\"fp\":1698,\"sr\":2174}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"38.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"38.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-ar@firefox.mozilla.org\":{\"version\":\"38.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ar@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-de@firefox.mozilla.org\":{\"version\":\"38.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-de@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.0");
user_pref("extensions.lastPlatformVersion", "38.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-ar@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-ar@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.0\",\"st\":1431342484000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.0\",\"st\":1433180504000,\"mt\":1431341923000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.0\",\"st\":1431342515000},\"langpack-de@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-de@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.0\",\"st\":1431342511000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.0\",\"st\":1431342516000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1424288290000,\"mt\":1420839872000}}}");
user_pref("gecko.buildID", "20150511103818");
user_pref("gecko.mstone", "38.0");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1433193813);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150511103818");
user_pref("media.gmp-manager.lastCheck", 1433193813);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 12485);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1433196960);
user_pref("toolkit.telemetry.previousBuildID", "20150511103818");
