# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1438854617);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1433193870);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1433194334);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1433194214);
user_pref("beacon.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.blocked", "{\"FWOQG7K0DIoR7IfVX99rIg==\":1,\"A2WNM340R8X/tRM8wN1MJQ==\":1,\"BcOAbuLi77y1AyoMYVR3Gg==\":1,\"XN0gzX5CZdmIYOEKmV0GVA==\":1,\"FD+HVOI6BkuwDht8E4Js3g==\":1,\"houJ+qdAQiE2vbUnKlgzdQ==\":1,\"5dPX2t2Xtq7V1dnRJu5irg==\":1,\"fN+l9WzvM5iUCIvEhEOYEQ==\":1,\"eZj1PVWGhpGfRIQaMb7GzA==\":1,\"24lPHRAkVJVXByz3pR2M/g==\":1,\"l9Y1wE6PrMx+3VW3g1dJ2Q==\":1,\"YsGswnfPkVNPe2jtF77GMA==\":1,\"t+kxXzmddH51Tb2XAG7VBg==\":1,\"+FGfbQqQI6PtMPCLu5tZ7Q==\":1,\"ZWzxIoKFFSaKQz/6tw9dvA==\":1}");
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "DE");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150629114848");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1438856459");
user_pref("browser.slowStartup.averageTime", 3180);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://seekm.github.io/speak/index.html");
user_pref("browser.startup.homepage_override.buildID", "20150629114848");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"ublock0-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"ublock0-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1438854561127");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1438854565487");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1438940965487");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1433189343788");
user_pref("datareporting.policy.firstRunTime", "1433188879593");
user_pref("datareporting.sessions.current.activeTicks", 8);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2913);
user_pref("datareporting.sessions.current.main", 391);
user_pref("datareporting.sessions.current.sessionRestored", 3294);
user_pref("datareporting.sessions.current.startTime", "1438856456188");
user_pref("datareporting.sessions.current.totalTime", 38);
user_pref("datareporting.sessions.currentIndex", 11);
user_pref("datareporting.sessions.previous.10", "{\"s\":1438856408720,\"a\":9,\"t\":47,\"c\":true,\"m\":122,\"fp\":3097,\"sr\":3863}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1438854496171,\"a\":21,\"t\":121,\"c\":true,\"m\":155,\"fp\":2683,\"sr\":2927}");
user_pref("datareporting.sessions.prunedIndex", 8);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"39.0\",\"DEVTOOLS_OS_ENUMERATED_PER_USER\":\"39.0\",\"DEVTOOLS_OS_IS_64_BITS_PER_USER\":\"39.0\",\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"39.0\",\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"39.0\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"39.0\"}");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"39.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"39.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-ar@firefox.mozilla.org\":{\"version\":\"39.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ar@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-de@firefox.mozilla.org\":{\"version\":\"39.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-de@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"uBlock0@raymondhill.net\":{\"version\":\"1.0.0.1\",\"type\":\"extension\",\"descriptor\":\"/home/guest-settings/.mozilla/firefox/h4d63tbs.default/extensions/uBlock0@raymondhill.net.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1438854328);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-ar@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-ar@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.0\",\"st\":1435580004000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.0\",\"st\":1438851574000,\"mt\":1435579394000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.0\",\"st\":1435580049000},\"langpack-de@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-de@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.0\",\"st\":1435580043000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"38.0\",\"st\":1435580049000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1424288290000,\"mt\":1420839872000}},\"app-profile\":{\"uBlock0@raymondhill.net\":{\"d\":\"/home/guest-settings/.mozilla/firefox/h4d63tbs.default/extensions/uBlock0@raymondhill.net.xpi\",\"e\":true,\"v\":\"1.0.0.1\",\"st\":1438854355000}}}");
user_pref("gecko.buildID", "20150629114848");
user_pref("gecko.mstone", "39.0");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1433193813);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150629114848");
user_pref("media.gmp-manager.lastCheck", 1438854560);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 12484);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1438856456);
user_pref("toolkit.telemetry.previousBuildID", "20150629114848");
